### PR TITLE
Added a VCL block to enable Drupal BigPipe support

### PR DESCRIPTION
**Pull request by operinko**

### CODE REVIEW

**Comment by Jancis** [comment]
This is an awesome addition! Is this tested or You could make a branch at https://github.com/wunderio/drupal-project-k8s and test this?

**Comment by operinko** [comment]
Not properly tested yet in our env (apart from actually seeing it working live on another site).
I'll make a branch and test it soon.

**Review by Jancis — CHANGES_REQUESTED** [review]
Requires change testing in drupal-project-k8s repository first

**Comment by Rade333** [comment]
Closing as the PR should be done to drupal-project-k8s repository

**Pull request closed without merging**
