### PR TITLE
SLT-792: Set enableServiceLinks to false in mariadb statefulsets

### PR DESCRIPTION
**Pull request by Rade333**
Changes proposed:
- add enableServiceLinks parameter as a setting to our forked mariadb chart, just like was done with elasticsearch in https://github.com/elastic/helm-charts/pull/542
- set the default value of mariadb.enableServiceLinks to `false` in our drupal chart

Background:
In namespaces with large amount of environments, having enableServiceLinks set to the default value of "true" causes the number of environment variables to get so high that bash becomes super slow.

### CODE REVIEW

**Comment by Jancis** [comment]
Any chance it could be exposed as a setting? In case someone still prefers having service links..

**Comment by Rade333** [comment]
> Any chance it could be exposed as a setting? In case someone still prefers having service links..

Sure, it could. But seeing as we don't provide such a setting in any other charts, I thought it would be good to stay consistent :) I suggest we would deploy this like this and create a separate ticket about exposing this parameter as a setting.

**Comment by Jancis** [comment]
https://github.com/wunderio/charts/blob/master/elasticsearch/values.yaml#L169

**Comment by Rade333** [comment]
Oh :D 
Okay, I'll make this a similar setting!

**Comment by Jancis** [comment]
`https://github.com/elastic/helm-charts/pull/542`
It was the OG issue we tracked down a while ago and somehow everyone forgot about mariadb. It's possible there are more related chart services that are affected.

**Comment by Rade333** [comment]
@Jancis PR updated with the parameter exposed as a setting.

> It's possible there are more related chart services that are affected.

I found that these files include PodSpec but do not have the enableServiceLinks parameter set:
- csi-rclone/templates/1.13-csi-controller-rclone.yaml
- csi-rclone/templates/1.13-csi-nodeplugin-rclone.yaml
- csi-rclone/templates/1.19-csi-controller-rclone.yaml
- csi-rclone/templates/1.19-csi-nodeplugin-rclone.yaml
- legacy_traefik/templates/deployment.yaml
- legacy_traefik/templates/storeconfig-job.yaml
- memcached/templates/deployment.yaml
- memcached/templates/statefulset.yaml
- mongodb/templates/arbiter/statefulset.yaml
- mongodb/templates/hidden/statefulset.yaml
- mongodb/templates/replicaset/statefulset.yaml
- rabbitmq/templates/statefulset.yaml
- redis/templates/redis-master-statefulset.yaml
- redis/templates/redis-slave-statefulset.yaml
- silta-cluster/templates/downscaler-cron.yaml
- silta-cluster/templates/k8s-controller-sidecars.yaml
- silta-downscaler/templates/downscaler-cron.yaml

I suggest we create a separate ticket for evaluating if those need to be updated as well, and keep this current ticket and PR scoped for mariadb.

**Comment by Jancis** [comment]
Thank You for checking those templates. Yes, create a separate (bundled) ticket for all those and this ticket will remain separate.

**Review by Jancis — APPROVED** [review]

**Comment by Jancis** [comment]
Merging this before drupal and frontend chart releases so they can pack the adjusted (and released) mariadb subchart.

**Pull request merged**
