### PR TITLE
Add annotation support for service accounts in csi-rclone chart

### PR DESCRIPTION
**Pull request by nuwang**
This PR
- adds support for service account annotations (so that IAM role annotations can be passed in)

### CODE REVIEW

**Review by Rade333 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

While updating the unittest plugin to a newer version is a good suggestion, doing it requires first fixing other chart tests, since I noticed some of them fail with the newer version.

Also, could you please provide tests for these new annotations.

**Comment by nuwang** [comment]
@Rade333 Thanks for the review. I'm removed the changes to helm-unit-test. While I added the unit test, I couldn't get it to pass, despite it matching an example here: https://github.com/helm-unittest/helm-unittest/blob/99033465fecf86ad082341f1bfb70bb247152252/test/data/v3/with-subsubcharts/charts/with-subsubchartssub/tests/deployment_test.yaml#L10

I suspect that this is because of the unit-test version. The metadata.annotations does seem to be getting the annotation value, but the assertion fails regardless.

**Comment by Rade333** [comment]
@nuwang thank you! the tests failed because the rbac template file includes multiple kubernetes resources, not only the service account definition. I added `documentIndex: 0` to your tests and now they pass at least locally for me. Still waiting for our CI pipelines to run more tests and then I can probably approve :)

**Review by Rade333 — APPROVED** [review]

**Comment by nuwang** [comment]
@Rade333 Aah interesting, thanks for that fix. I assumed documentIndex=0 was implicit, as I was able to assert on metadata.name, just not annotations. Glad it's all working now.

**Pull request merged**
