### PR TITLE
Add support for preinstall and preupgrade hooks to frontend

### PR DESCRIPTION
**Pull request by badrange**

### CODE REVIEW

**Comment by Jancis** [comment]
You can't mix pre-install/upgrade and post-install(upgrade) hooks in the same resource as the resource will be deployed and run in both cases. This means, both sets of commands will be executed twice. The install and upgrade actions are merged because it only gets executed in either case.

**Review by Jancis — CHANGES_REQUESTED** [review]
You can't mix pre-install/upgrade and post-install(upgrade) hooks in the same resource as the resource will be deployed and run in both cases. This means, both sets of commands will be executed twice. The install and upgrade actions are merged because it only gets executed in either case.

**Comment by Jancis** [comment]
I believe this can be closed

**Comment by badrange** [comment]
Yes! I'll reopen this if it becomes relevant in some form or other.

**Pull request closed without merging**
